# Mosquitto MQTT Broker config
# Jalankan: mosquitto -c mosquitto.conf

listener 1883
allow_anonymous true

# Untuk produksi: aktifkan autentikasi
# password_file /etc/mosquitto/passwd
# allow_anonymous false

# Logging
log_dest stdout
log_type all
