; ============================================================
; CNC IoT Monitor - PlatformIO Configuration
; ESP32 + ACS712 (5x) + DS18B20 (2x) + Relay + MQTT
; ============================================================

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -I include
    -DMQTT_MAX_PACKET_SIZE=512
    -DMQTT_KEEPALIVE=60

lib_extra_dirs = lib

lib_deps =
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    knolleary/PubSubClient @ ^2.8.0
    ; Preferences & WiFi sudah built-in di ESP32 framework
